pipeline {
  agent {
    docker {
      image 'maven:3.8.1-adoptopenjdk-11'
      args '--user root -v /root/.m2/repository:/root/.m2/repository' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('Checkout') {
        steps {
            git branch: 'main', url: 'https://github.com/ssprkarri/Jenkins-Zero-To-Hero' 
        }
    }
    stage('Build and Run') {
        steps {
            script {
                // Build and run java code
                sh 'multi-stage-multi-agent-test/javac HelloWorld.java'
                sh 'multi-stage-multi-agent-test/java HelloWorld'
                }
            }
    }
  }
}
