pipeline {
  agent {
    docker {
      image 'openjdk:latest'
      args '--user root -v /root/.m2/repository:/root/.m2/repository' // mount Docker socket to access the host's Docker daemon
    }
  }
  stages {
    stage('Checkout') {
        steps {
            git branch: 'main', url: 'https://github.com/ssprkarri/Jenkins-Zero-To-Hero' 
        }
    }
    stage('Build and Run') {
        steps {
            script {
                // Build and run java code
                sh 'javac multi-stage-multi-agent-test/HelloWorld.java'
                sh 'java ./multi-stage-multi-agent-test/HelloWorld'
                }
            }
    }
    stage('Debug') {
        steps {
            script {
                sh 'ls -l'
                sh 'cat ./multi-stage-multi-agent-test/HelloWorld.java'
                sh 'cat ./multi-stage-multi-agent-test/HelloWorld.class'
            }
        }
    }
  }
}
