pipeline {
  agent {
    docker { image 'maven:latest' }
  }
  stages {
    stage('Checkout') {
        steps {
            git branch: 'main', url: 'https://github.com/ssprkarri/Jenkins-Zero-To-Hero' 
        }
    }
    stage('Build and Run') {
        steps {
            script {
                // Compile the Java code
                sh 'javac HelloWorld.java'

                // Run the Java application
                sh 'java HelloWorld.java'
                }
            }
    }
  }
}
